name: Deploy Spring Boot Application

on:
  push:
    branches:
      - master

jobs:
  build-run-container:
    runs-on: self-hosted

    container:
      image: eclipse-temurin:25-jdk
      options: --user root

    steps:
      - name: Prepare environment
        run: |
          apt update
          apt install -y git docker.io lsof

      - name: Clone repository
        run: |
          git clone http://gitea:3000/Jevadmin/mazeApi.git .
          git checkout $GITHUB_SHA

      - name: Verify Java version
        run: java -version

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run unit and integration tests
        run: |
          ./gradlew test --info
        continue-on-error: false

      - name: Return test reports
        run: |
          ls -l build/reports/tests/test

      - name: Build Spring Boot JAR
        run: ./gradlew clean bootJar

      - name: Build Docker image
        run: |
          docker build \
            --build-arg JAR_FILE=build/libs/*.jar \
            -t mazeapi:latest .

      - name: Stop any running container and free port
        run: |
          if docker ps -a -q -f name=mazeapi | grep -q .; then
            docker rm -f mazeapi
            echo "Removed existing container 'mazeapi'"
          fi

          if lsof -i :808; then
            echo "Port 808 still in use, killing processes..."
            fuser -k 808/tcp
          fi

          sleep 2

      - name: Run new container
        run: |
          docker run -d \
            --name mazeapi \
            -p 808:8080 \
            mazeapi:latest

      - name: Show container logs
        run: docker logs --tail=100 mazeapi