name: Deploy springboot application

on:
  push:
    branches:
      - master

jobs:
  build-run-container:
    runs-on: self-hosted

    container:
      image: eclipse-temurin:21-jdk
      options: --user root

    steps:
      - name: Prepare environment
        run: |
          apt update
          apt install -y git docker.io

      - name: Clone repository
        run: |
          git clone http://gitea:3000/Jevadmin/mazeApi.git .
          git checkout $GITHUB_SHA

      - name: Verify Java
        run: java -version

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Spring Boot JAR
        run: ./gradlew clean bootJar

      - name: Build Docker image
        run: |
          docker build \
            --build-arg JAR_FILE=build/libs/*.jar \
            -t mazeapi:latest .

      - name: Stop existing container
        run: |
          docker rm -f mazeapi || true

      - name: Run new container
        run: |
          docker run -d \
            --name mazeapi \
            -p 8080:8080 \
            mazeapi:latest

      - name: Show container logs
        run: docker logs --tail=100 mazeapi