name: Deploy Spring Boot Application

on:
  push:
    branches:
      - master

jobs:
  build-run-container:
    runs-on: self-hosted

    container:
      image: eclipse-temurin:25-jdk
      options: --user root

    steps:
      - name: Prepare environment
        run: |
          apt update
          apt install -y git docker.io

      - name: Clone repository
        run: |
          git clone http://gitea:3000/Jevadmin/mazeApi.git .
          git checkout $GITHUB_SHA

      - name: Verify Java
        run: java -version

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Spring Boot JAR
        run: ./gradlew clean bootJar

      - name: Build Docker image
        run: |
          docker build \
            --build-arg JAR_FILE=build/libs/*.jar \
            -t mazeapi:latest .

      - name: Stop any existing container
        run: |
          # Stop and remove any container named 'mazeapi', running or exited
          if docker ps -a -q -f name=mazeapi | grep -q .; then
            docker rm -f mazeapi
            echo "Removed existing container 'mazeapi'"
          fi
          # Optional extra safety: give Docker time to free the port
          sleep 2

      - name: Run new container
        run: |
          docker run -d \
            --name mazeapi \
            -p 8080:8080 \
            mazeapi:latest

      - name: Show container logs
        run: docker logs --tail=100 mazeapi