name: Build and Run Docker Container Java 25

on:
  push:
    branches:
      - master
# test
jobs:
  build-run-container:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 25
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build JAR
        run: ./gradlew clean bootJar

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build --build-arg JAR_FILE=build/libs/*.jar \
                       -t mazeapi-java25:latest .

      - name: Run Docker Container
        run: |
          # Stop any running container with the same name
          if [ $(docker ps -aq -f name=mazeapi-container) ]; then
            docker rm -f mazeapi-container
          fi
          # Run a new container
          docker run -d --name mazeapi-container -p 8080:8080 mazeapi-java25:latest

      - name: Show container logs
        run: docker logs -f mazeapi-container