name: Deploy Spring Boot Application

on:
  push:
    branches:
      - master

jobs:
  build-run-container:
    runs-on: self-hosted

    container:
      image: eclipse-temurin:25-jdk
      options: --user root

    steps:
      - name: Prepare environment
        run: |
          mkdir -p /workdir/mazeApi
          rm -rf /workdir/mazeApi/*
          apt update
          apt install -y git docker.io lsof

      - name: Clone repository
        run: |
          git clone http://gitea:3000/Jevadmin/mazeApi.git /workdir/mazeApi
          cd /workdir/mazeApi
          git checkout $GITHUB_SHA

      - name: Verify Java version
        run: java -version
        working-directory: /workdir/mazeApi

      - name: Make Gradle executable
        run: chmod +x ./gradlew
        working-directory: /workdir/mazeApi

      - name: Run unit and integration tests
        run: ./gradlew test --info
        working-directory: /workdir/mazeApi
        continue-on-error: false

      - name: Build Spring Boot JAR
        run: ./gradlew clean bootJar
        working-directory: /workdir/mazeApi

      - name: Build Docker image
        run: docker build -t mazeapi:latest /workdir/mazeApi
        working-directory: /workdir/mazeApi

      - name: Stop any running container and free port
        run: |
          if docker ps -a -q -f name=mazeapi | grep -q .; then
            docker rm -f mazeapi
          fi

          if lsof -i :808; then
            fuser -k 808/tcp
          fi

          sleep 2

      - name: Run new container
        run: |
          docker run -d \
            --name mazeapi \
            -p 808:8080 \
            mazeapi:latest

      - name: Show container logs
        run: docker logs --tail=100 mazeapi

      - name: Clean workspace
        run: rm -rf /workdir/mazeApi/*